"""
Replay a LabVIEW-demo CSV template into a live-updating CSV file.

This script is the temporary stand-in for the future real source:

    LabVIEW demo template CSV -> this writer -> live CSV on a client relay PC
    -> mqtt_bridge_sender.py --mode csv-last-row -> MQTT / HTTP -> PrediTeq

Why not publish directly here?
    Because the real future architecture still needs the same CSV-reading bridge.
    By keeping that bridge unchanged, this demo step is easy to remove later.
"""

from __future__ import annotations

import argparse
import csv
import time
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    default_input = (
        Path(__file__).resolve().parent
        / "sample_data"
        / "ARO-01_labview_demo_template.csv"
    )
    default_output = (
        Path(__file__).resolve().parent
        / "sample_data"
        / "ARO-01_labview_demo_live.csv"
    )

    parser = argparse.ArgumentParser(
        description="Append LabVIEW-demo rows to a live CSV file with fresh timestamps."
    )
    parser.add_argument(
        "--input",
        default=str(default_input),
        help="Template CSV generated by generate_labview_demo_csv.py",
    )
    parser.add_argument(
        "--output",
        default=str(default_output),
        help="Live CSV file that mqtt_bridge_sender.py will read in csv-last-row mode",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="Seconds between appended rows. Use < 1.0 only for compressed demos.",
    )
    parser.add_argument(
        "--loop",
        action="store_true",
        help="Loop back to the first template row after reaching the end",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=0,
        help="Optional cap for appended rows. 0 = no cap.",
    )
    parser.add_argument(
        "--machine-id",
        default="",
        help="Optional machine code override written into the live CSV",
    )
    parser.add_argument(
        "--source-label",
        default="",
        help="Optional source override written into the live CSV",
    )
    return parser.parse_args()


def now_iso_utc() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def read_template_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"Template CSV is empty: {path}")
    return [
        {
            str(key).strip(): value.strip() if isinstance(value, str) else value
            for key, value in row.items()
            if key not in (None, "")
        }
        for row in rows
    ]


def build_output_fieldnames(template_fieldnames: list[str]) -> list[str]:
    clean = [name for name in template_fieldnames if name]
    if "time" in clean:
        return clean
    if "machine_code" in clean:
        index = clean.index("machine_code") + 1
        return clean[:index] + ["time"] + clean[index:]
    return ["time"] + clean


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).resolve()
    output_path = Path(args.output).resolve()
    rows = read_template_rows(input_path)

    fieldnames = build_output_fieldnames(list(rows[0].keys()))
    output_path.parent.mkdir(parents=True, exist_ok=True)

    appended = 0
    machine_override = args.machine_id.strip().upper()
    source_override = args.source_label.strip()

    print(f"Template rows loaded : {len(rows)}")
    print(f"Live CSV output      : {output_path}")
    print(f"Interval             : {args.interval:.3f} s")
    if args.interval < 1.0:
        print("Note: interval < 1.0 compresses the demo only; the real target remains 1 Hz.")

    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        handle.flush()

        while True:
            for row in rows:
                live_row = dict(row)
                live_row["time"] = now_iso_utc()
                if machine_override:
                    live_row["machine_code"] = machine_override
                if source_override:
                    live_row["source"] = source_override

                writer.writerow({name: live_row.get(name, "") for name in fieldnames})
                handle.flush()
                appended += 1

                print(
                    f"[{live_row['time']}] appended row {appended} "
                    f"phase={live_row.get('phase', '?')} "
                    f"rms={live_row.get('vibration_mm_s', '?')} "
                    f"power={live_row.get('motor_power', '?')} "
                    f"load={live_row.get('charge', '?')}"
                )

                if args.max_rows and appended >= args.max_rows:
                    print("Reached --max-rows limit, stopping.")
                    return 0

                time.sleep(max(args.interval, 0.01))

            if not args.loop:
                break

    print(f"Replay complete. Appended {appended} rows into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
